version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    ports:
      - 8080:8080
    volumes:
      - file_config:/config
      - file_data:/data
    restart: unless-stopped

volumes:
  file_data:
  file_config: