CREATE TABLE modulos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL 
);

INSERT INTO modulos (nombre) VALUES
('DESPLIEGE'),
('ENTORNO CLIENTE'),
('ENTORNO SERVIDOR'),
('PROGRAMACION');